import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import  "./globals.css";
import Navbar from "../components/Navbar/navbar";
import Footer from "../components/Footer/footer";

const roboto = Roboto({ 
  weight: '700',
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aces Cigars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
